Repository input-output-hk/jormungandr, pull requests merged in 2021-06, with the labels that each got.

#3340 ci: fix release pipelines issues
  .github/workflows/release.yml
Labels: A-ci, bug

#3329 Improve rest utils
  testing/jormungandr-testing-utils/src/testing/node/legacy/rest.rs
  testing/jormungandr-testing-utils/src/testing/node/rest/raw.rs
  testing/jormungandr-testing-utils/src/testing/node/rest/settings.rs
Labels: A-tests

#3348 ci: was using the wrong key in Slack notifications
  .github/workflows/release.yml
Labels: A-ci, bug

#3357 Update Cargo.lock
  Cargo.lock
Labels: dependencies

#3322 tests: use rest api for wait for date
  testing/jormungandr-integration-tests/src/jormungandr/bft/mempool/v0.rs
  testing/jormungandr-integration-tests/src/jormungandr/bft/mempool/v1.rs
  testing/jormungandr-integration-tests/src/jormungandr/fragments.rs
  testing/jormungandr-integration-tests/src/jormungandr/genesis/rewards.rs
  testing/jormungandr-integration-tests/src/jormungandr/mempool/fragments_dump.rs
  testing/jormungandr-integration-tests/src/jormungandr/vit/private.rs
  testing/jormungandr-integration-tests/src/jormungandr/vit/public.rs
  testing/jormungandr-integration-tests/src/non_functional/fragment.rs
  testing/jormungandr-integration-tests/src/non_functional/voting/private/mod.rs
  testing/jormungandr-integration-tests/src/non_functional/voting/public/mod.rs
  testing/jormungandr-testing-utils/src/testing/fragments/generator.rs
  testing/jormungandr-testing-utils/src/testing/node/time.rs
  testing/mjolnir/src/mjolnir_app/fragment/standard/all.rs
Labels: A-tests

#3349 rest: log all requests
  jormungandr/src/rest/mod.rs
Labels: A-jormungandr, enhancement, subsys-logging, subsys-rest

#3369 rest: log B3 headers information
  Cargo.lock
  jormungandr/Cargo.toml
  jormungandr/src/rest/mod.rs
Labels: A-jormungandr, subsys-logging, subsys-rest

#3370 Mempool update
  Cargo.lock
  jormungandr/src/blockchain/process.rs
  jormungandr/src/blockchain/storage.rs
  jormungandr/src/fragment/logs.rs
  jormungandr/src/fragment/pool.rs
  jormungandr/src/fragment/process.rs
  jormungandr/src/fragment/selection.rs
  jormungandr/src/intercom.rs
  jormungandr/src/network/bootstrap.rs
Labels: subsys-consensus, subsys-mempool

#3393 add discrimination to settings endpoint
  jormungandr-lib/src/interfaces/settings.rs
  jormungandr/src/rest/v0/logic.rs
Labels: A-api, enhancement
